# Generated by Django 3.2.23 on 2024-03-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General_Knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_knowledge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='category',
        ),
    ]
