# Generated by Django 3.2.23 on 2024-03-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General_Knowledge', '0002_auto_20240321_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='General_Knowledge.categories'),
        ),
    ]
