# Generated by Django 4.2.3 on 2024-03-28 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("General_Knowledge", "0003_general_knowledge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategories",
            name="category",
        ),
        migrations.DeleteModel(
            name="General_Knowledge",
        ),
        migrations.DeleteModel(
            name="Subcategories",
        ),
    ]
