# Generated by Django 3.2.23 on 2024-09-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General_Knowledge', '0006_general_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_knowledge',
            name='category',
            field=models.ForeignKey(default='General Knowledge', on_delete=django.db.models.deletion.CASCADE, to='General_Knowledge.categories'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(default='General Knowledge', on_delete=django.db.models.deletion.CASCADE, to='General_Knowledge.categories'),
        ),
    ]
