# import requests to use the API for edu quiz
import requests

# import html to handle potential HTML entities and aid rendering for create_subcategory_object
import html

# import random to shuffle questions & choices rendered in the form
import random

# import json to work with the data retrieved from the open trivia db API
import json

# import models
from .models import *

# import apps to dynamically fetch a model in category_objects() for the detail() view
from django.apps import apps      

# import Http404 to raise an error message if a model is not located in category_objects()
from django.http import Http404

#######################################################################################
#######################################################################################


# define a function that returns the json response for Open Trivia DB
def get_json_categories():
    """
    Retrieve a specific category from the Open Trivia DB API.

    :param name: None.
    :type name: str
    :return: The JSON response from the Open Trivia DB API.
    :rtype: dict
    """

    # get Category Lookup url
    category_lookup = 'https://opentdb.com/api_category.php'
    # store url in a variable as a json response
    response = requests.get(category_lookup)
    if response.status_code == 200:
        json_response = response.json()
    
        # write Categories to a json file
        # use an indent to ensure each category prints on separate lines
        with open("quiz_categories.json", "w") as f:
            json.dump(json_response, f, indent=4)

        return json_response
    
    else:
        # print error if unsuccessful request
        # return None to signal that there's no valid data to work with
        error_message = f"Unable to retrieve the specific category - Status code:{response.status_code}"
        print(error_message)
        return None
    

# define a function that returns the json response for Open Trivia DB when requesting a specific category
def get_specific_json_category(quantity: int, category: int) -> dict:
    """
    Retrieve a specific category from the Open Trivia DB API.

    :param name: A description of the quantity and category.
    :type name: str
    :return: The JSON response from the Open Trivia DB API.
    :rtype: dict
    """
    api_url = f"https://opentdb.com/api.php?amount={quantity}&category={category}"
    response = requests.get(api_url)

    # a successful request will give a 200 status code
    # get a json response or else there will only be a status code
    if response.status_code == 200:
        json_response = response.json()

        # write chosen category to a json file - has to be after getting a json response (converting to a dictionary)
        # - because writing to a file needs to be done on a serialisable object
        # use an indent to ensure each category prints on separate lines
        with open("chosen_quiz_category.json", "w") as f:
            json.dump(json_response, f, indent=4)

        return json_response

    else:
        # print error if unsuccessful request
        # return None to signal that there's no valid data to work with
        error_message = f"Unable to retrieve the specific category - Status code:{response.status_code}"
        print(error_message)
        return None 


# rearrange the options of answers
# use the random module & its shuffle function to rearrange
# return a list of choices
def mix_choices(choices: list) -> list:
    """
    Mixes the choices for each question in a quiz.

    :param choices: A list of answer choices for a question.
    :type choices: list
    :return: A shuffled list of choices.
    :rtype: list
    """
    random.shuffle(choices)
    return choices

# define a function that returns the django pk for the next question in the quiz
def get_next_question_id(category_name, question_id, question_selection_pks):
    """
    Retrieves the next question ID based on the current question ID and the list of question primary keys.

    :param question_id: The ID of the current question.
    :type question_id: int
    :param question_selection_pks: A list of primary keys representing available questions.
    :type question_selection_pks: list
    :return: The ID of the next question.
    :rtype: int
    """
    # iterate over the list of question ids in question_selection_ids from utils.category_objects()
    # - to check if the id generated by django matches the question_id parameter in the url
    # - & display the specific question that matches the question_id in the URL
    # question_pk refers to the automatically generated primary key (id) of each question in question_selection,
    # and question_id is the identifier passed in the URL
    # use enumerate to give each question in the selection an idx
    for i, question_pk in enumerate(question_selection_pks, start=1):
        if question_pk == question_id:
            # save i to a variable. previously it wasn't being preserved properly for the last question
            # - giving an idx out of range error
            # so use the variable instead of i to index the next pk
            # previously i represented the index of the current iteration in the conditional with len,
            # - which may be different from the desired index for the next question's primary key
            next_idx_for_pk = i

            # return the next question if its idx is less than / equal to the length of question_selection
            if next_idx_for_pk < len(question_selection_pks):
                return question_selection_pks[next_idx_for_pk]
            else:
                return None


# define a function that will retrieve category names based on the category id for it in the json response
def get_category_names(response: dict) -> list:
    """
    Finds the question ID for the next question in the quiz.

    :param response: A list containing relevant information about the quiz.
    :type response: list
    :return: A dictionary with details about the next question (e.g., question ID, category).
    :rtype: dict
    """
    # Get the trivia categories values from the dictionary provided in the JSON response
    # Place an empty list as the default argument if the key is not found - this avoids errors in subsequent code
    trivia_categories = response.get("trivia_categories", [])

    # specify the id of the categories to include in the Entertainment app's quizzes
    selected_category_id = [12, 11, 15]

    # collect the categories based on selected_category_id
    selected_categories = [category for category in trivia_categories if category.get("id") in selected_category_id]    
    print(f"selected_categories:{selected_categories}")

    # initialise a variable for the chosen category from the json response
    selected_category = None

    # create an empty list for the category names
    category_names =[]

    # iterate over trivia categories to find the category id specified 
    for category in selected_categories:
        # check if the id in selected_category_id is in the trivia_categories
        if category.get("id") in selected_category_id:
            # assign the current category to the selected_category variable
            selected_category = category
            # use this to get music only and remove entertainment.
            new_value = category['name'].split(':')[1].strip()
            # Update the dictionary with the new value
            category['name'] = new_value
                        
            print(f"selected_category:{selected_category}")       
            
            # get the name of the category if the id exists for the selected category
            # append each category name to a list
            if selected_category:
                category_name = selected_category.get("name")
                category_names.append(category_name) 

    # return the list of category_names
    return category_names


# define a function that returns the queryset for 10 random objects from the database for each category 
# https://stackoverflow.com/questions/27270958/patch-multiple-methods-from-different-modules-using-python-mock#:~:text=The%20short%20answer%20is%20no%20you%20cannot%20use,one%20of%20the%20time%20by%20single%20patch%20calls.
def category_objects(request, category_name):
    """
    Retrieves the category queryset from the database based on its category name.

    :param request: The HTTP request object (optional, if needed).
    :type request: HttpRequest
    :param category_name: The name of the category.
    :type category_name: str
    :return: A queryset of objects for the specified category.
    :rtype: QuerySet
    """
    # use the category_name selected on edu_quiz.html to determine the model to get questions from
    # replace spaces and '&' in the event category names have spaces to create a valid model name
    model_name = category_name.replace(" ", "_").replace("&", "and") 
    print('model name : ', model_name)   

    # use a try-except block to find a model that matches the category name
    # use globals()[model_name], it directly accesses the global namespace and doesn't rely on the apps registry. 
    # this approach was more flexible than apps.get_model module since the model name was modified when replacing '&' 
    # - this is not directly compatible with how models are stored in the apps registry
    # the apps module worked to dynamically retrieve a model when only ' ' was being replaced
    # - dynamically:instead of explicitly specifying a fixed model in the code, generate or determine the model to use at runtime based on certain conditions/data
    # use the globals() function to access the global symbol table in Python & retrieve the model with the model name as a key
    # - Note: it relies on the fact that the model class is in the global namespace
    try:        
        model = globals()[model_name]
        print('model name globals: ', model) 

    # raise an error if the model is not found
    except LookupError:
        raise Http404("Cannot locate the model for the selected category.")

    # get the 50 questions for the specific category
    # https://docs.djangoproject.com/en/3.2/topics/db/queries/#retrieving-all-objects    
    all_questions = model.objects.all()

    # create a list containing the pk for each obj
    category_question_ids = [question.id for question in all_questions]

    # get the ids for the selection of 10 questions
    # use random to select 10 questions
    # https://docs.python.org/3.7/library/random.html?highlight=random#random.sample
    # note: random.sample requires a list as its first argument
    question_selection_ids = random.sample(category_question_ids, 10)
    
    # save the question_selection in a session then it will be accessible in selection view as well
    # https://stackoverflow.com/questions/59776172/how-to-pass-querysets-or-the-context-dictronary-from-one-view-to-another-view
    request.session['question_selection_ids'] = question_selection_ids
    
    # filter the objects based on question_selection_ids
    # https://docs.djangoproject.com/en/3.2/topics/db/queries/#the-pk-lookup-shortcut
    question_selection = model.objects.filter(pk__in=question_selection_ids)        

    # return the selected 10 questions from thr database
    return question_selection