# Generated by Django 4.2.3 on 2024-02-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("choices", models.TextField(blank=True, default=list)),
                ("correct_answer", models.TextField()),
            ],
        ),
    ]
