# Generated by Django 3.2.23 on 2024-03-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.TextField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='Education.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Science_and_Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('category', models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='Education.categories')),
                ('subcategory', models.ForeignKey(default='Science & Nature', on_delete=django.db.models.deletion.CASCADE, to='Education.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Mythology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('category', models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='Education.categories')),
                ('subcategory', models.ForeignKey(default='Mythology', on_delete=django.db.models.deletion.CASCADE, to='Education.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('category', models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='Education.categories')),
                ('subcategory', models.ForeignKey(default='History', on_delete=django.db.models.deletion.CASCADE, to='Education.subcategories')),
            ],
        ),
    ]
