# Generated by Django 4.2.3 on 2024-02-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("choices", models.TextField(blank=True, default=list)),
                ("correct_answer", models.TextField()),
            ],
        ),
    ]
