# Generated by Django 4.2.3 on 2024-02-05 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Education", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quiz",
            new_name="Mythology",
        ),
    ]
