# Generated by Django 3.2.23 on 2024-03-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science_and_Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='Education.categories')),
                ('subcategory', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='Education.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Mythology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='Education.categories')),
                ('subcategory', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Education.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('category', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='Education.categories')),
                ('subcategory', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='Education.subcategories')),
            ],
        ),
    ]
