# Generated by Django 3.2.23 on 2024-09-21 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0006_science_and_nature_mythology_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='category',
            field=models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='Education.categories'),
        ),
        migrations.AlterField(
            model_name='history',
            name='subcategory',
            field=models.ForeignKey(default='History', on_delete=django.db.models.deletion.CASCADE, to='Education.subcategories'),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='category',
            field=models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='Education.categories'),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='subcategory',
            field=models.ForeignKey(default='Mythology', on_delete=django.db.models.deletion.CASCADE, to='Education.subcategories'),
        ),
        migrations.AlterField(
            model_name='science_and_nature',
            name='category',
            field=models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='Education.categories'),
        ),
        migrations.AlterField(
            model_name='science_and_nature',
            name='subcategory',
            field=models.ForeignKey(default='Science_and_Nature', on_delete=django.db.models.deletion.CASCADE, to='Education.subcategories'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='Education.categories'),
        ),
    ]
