# Generated by Django 3.2.23 on 2024-03-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.TextField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default='Entertainment', on_delete=django.db.models.deletion.CASCADE, to='Entertainment.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('category', models.ForeignKey(default='Entertainment', on_delete=django.db.models.deletion.CASCADE, to='Entertainment.categories')),
                ('subcategory', models.ForeignKey(default='Video_Games', on_delete=django.db.models.deletion.CASCADE, to='Entertainment.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('category', models.ForeignKey(default='Entertainment', on_delete=django.db.models.deletion.CASCADE, to='Entertainment.categories')),
                ('subcategory', models.ForeignKey(default='Music', on_delete=django.db.models.deletion.CASCADE, to='Entertainment.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('category', models.ForeignKey(default='Entertainment', on_delete=django.db.models.deletion.CASCADE, to='Entertainment.categories')),
                ('subcategory', models.ForeignKey(default='Film', on_delete=django.db.models.deletion.CASCADE, to='Entertainment.subcategories')),
            ],
        ),
    ]
