# Generated by Django 3.2.23 on 2024-03-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entertainment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.RemoveField(
            model_name='film',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='music',
            name='category',
        ),
        migrations.RemoveField(
            model_name='music',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='video_games',
            name='category',
        ),
        migrations.RemoveField(
            model_name='video_games',
            name='subcategory',
        ),
    ]
