# Generated by Django 3.2.23 on 2024-03-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entertainment', '0003_subcategories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='Entertainment.categories'),
        ),
        migrations.AddField(
            model_name='film',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Entertainment.subcategories'),
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='Entertainment.categories'),
        ),
        migrations.AddField(
            model_name='music',
            name='subcategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Entertainment.subcategories'),
        ),
        migrations.AddField(
            model_name='video_games',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='Entertainment.categories'),
        ),
        migrations.AddField(
            model_name='video_games',
            name='subcategory',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Entertainment.subcategories'),
        ),
    ]
