# Generated by Django 4.2.3 on 2024-03-28 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Entertainment", "0003_film_music_video_games"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="category",
        ),
        migrations.RemoveField(
            model_name="music",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="subcategories",
            name="category",
        ),
        migrations.RemoveField(
            model_name="video_games",
            name="category",
        ),
        migrations.RemoveField(
            model_name="video_games",
            name="subcategory",
        ),
        migrations.DeleteModel(
            name="Film",
        ),
        migrations.DeleteModel(
            name="Music",
        ),
        migrations.DeleteModel(
            name="Subcategories",
        ),
        migrations.DeleteModel(
            name="Video_Games",
        ),
    ]
